### ISSUE TITLE
Able to get around FTB claims 

### ISSUE THREAD

**Issue by deadlyaaher** [Direwolf20-MC/BuildingGadgets2#66]
**Describe the bug**
Exchange tool and destruction tool are able to get around protection claims on servers 

**To Reproduce**
Use tools in another players claim

**Comment by MichaelHillcox** [comment]
What mod version?

**Comment by jaynotgay** [comment]
Maybe include abit more info like- mod version, and what actual mod your using for protection? xD

**Comment by Direwolf20-MC** [comment]
Confirmed bug, need to ask FTB team how to fix :)

**Comment by Nidaelie** [comment]
Any eta on fix?

**Comment by desht** [comment]
Hey Dire, FTB team here :smile: 

From what I can tell (unless I've missed it somewhere), you're not currently firing Forge block place/break events before placing or breaking any blocks.  Without events, FTB Chunks can't intercept and prevent player actions in claimed chunks.

**Comment by Devilmedic** [comment]
Is there any fix for this yet?

**Comment by Direwolf20-MC** [comment]
Should be fixed now, thanks! Sorry for the delay!

**Comment by bishbosh69420** [comment]
> Should be fixed now, thanks! Sorry for the delay!

currently using building gadgets and ftb claims in 1.20.1 and it is not working, is there some config i need to edit to allow it to work?

**Comment by Natsumi-x** [comment]
> > Should be fixed now, thanks! Sorry for the delay!
> 
> currently using building gadgets and ftb claims in 1.20.1 and it is not working, is there some config i need to edit to allow it to work?

Still broken on 1.20.1. But there hasn't been an update put out on curseforge for this version of MC since last year.
